project_id = "myqjmfficlxrefjhlewo"

[functions.send-whatsapp-notification]
verify_jwt = true

[functions.owner-onboarding]
verify_jwt = true

[functions.submit-owner-application]
verify_jwt = false

[functions.invite-approved-owner]
verify_jwt = true
