import { useEffect, useMemo } from "react";
import { Helmet } from "react-helmet-async";
import { useNavigate, useSearchParams } from "react-router-dom";
import { ArrowRight, Building2, Loader2, MapPin, MessageCircle, RotateCcw, Search } from "lucide-react";
import Header from "@/components/Header";
import MapSection from "@/components/MapSection";
import SportComplexCard from "@/components/SportComplexCard";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useAuth } from "@/hooks/useAuth";
import { useComplexes, SportComplexData } from "@/hooks/useComplexes";
import { useProfile } from "@/hooks/useProfile";
import { ResultsToolbar } from "@/components/discovery/ResultsToolbar";
import { SearchIntentBar } from "@/components/discovery/SearchIntentBar";
import { SportRail } from "@/components/discovery/SportRail";
import { DiscoveryCriteria, DiscoverySort, DiscoveryView } from "@/components/discovery/discovery-types";

const today = new Date().toISOString().slice(0, 10);
const toBoolean = (value: string | null) => value === "true";
const validSort = (value: string | null): DiscoverySort => value === "price" || value === "name" ? value : "relevance";
const validView = (value: string | null): DiscoveryView => value === "list" ? "list" : "map";
const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();

const Index = () => {
  const navigate = useNavigate(); const [params, setParams] = useSearchParams();
  const { user } = useAuth(); const { isOwner } = useProfile(); const { complexes, loading, error } = useComplexes(user?.id ?? null, false);
  const criteria: DiscoveryCriteria = { sport: params.get("sport") || "todos", query: params.get("q") || "", date: params.get("date") || today, time: params.get("time") || "", roofOnly: toBoolean(params.get("roof")), lightingOnly: toBoolean(params.get("lighting")), sort: validSort(params.get("sort")), view: validView(params.get("view")) };
  useEffect(() => { if (isOwner) navigate("/dashboard", { replace: true }); }, [isOwner, navigate]);
  const updateCriteria = (patch: Partial<DiscoveryCriteria>) => { const next = { ...criteria, ...patch }; const nextParams = new URLSearchParams(); if (next.sport !== "todos") nextParams.set("sport", next.sport); if (next.query.trim()) nextParams.set("q", next.query.trim()); if (next.date !== today) nextParams.set("date", next.date); if (next.time) nextParams.set("time", next.time); if (next.roofOnly) nextParams.set("roof", "true"); if (next.lightingOnly) nextParams.set("lighting", "true"); if (next.sort !== "relevance") nextParams.set("sort", next.sort); if (next.view !== "map") nextParams.set("view", next.view); setParams(nextParams, { replace: true }); };
  const filtered = useMemo(() => complexes.filter((complex) => { const courts = complex.courts ?? []; const text = normalize([complex.name, complex.neighborhood ?? "", complex.address, ...courts.map((court) => court.sport)].join(" ")); return (criteria.sport === "todos" || courts.some((court) => normalize(court.sport).includes(normalize(criteria.sport)))) && (!criteria.query || text.includes(normalize(criteria.query))) && (!criteria.roofOnly || courts.some((court) => court.has_roof)) && (!criteria.lightingOnly || courts.some((court) => court.has_lighting)); }).sort((left, right) => { if (criteria.sort === "name") return left.name.localeCompare(right.name, "es"); if (criteria.sort === "price") { const price = (item: SportComplexData) => Math.min(...(item.courts ?? []).map((court) => court.hourly_price).filter((value): value is number => typeof value === "number" && value > 0), Infinity); return price(left) - price(right); } return left.name.localeCompare(right.name, "es"); }), [complexes, criteria]);
  return <><Helmet><title>Cancha Libre | Encontrá dónde jugar en Jujuy</title><meta name="description" content="Encontrá complejos deportivos en San Salvador de Jujuy." /><meta property="og:image" content="/hero-canchalibre-night.png" /></Helmet><div className="min-h-screen bg-background"><Header /><main>
    <section className="relative min-h-[470px] overflow-visible bg-emerald-950 pb-28 pt-12 text-white md:min-h-[510px] md:pb-32 md:pt-16"><img src="/hero-canchalibre-night.png" alt="Cancha deportiva iluminada al anochecer" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-slate-950/90 via-slate-950/65 to-emerald-950/35" /><div className="container relative mx-auto px-4"><div className="max-w-[610px]"><p className="mb-4 flex items-center gap-2 text-sm font-medium text-emerald-200"><MapPin className="h-4 w-4" />Canchas y complejos en San Salvador de Jujuy</p><h1 className="text-5xl font-extrabold leading-[.95] tracking-tight md:text-6xl">Encontrá dónde <span className="text-emerald-300">jugar.</span></h1><p className="mt-5 max-w-[500px] text-base leading-relaxed text-white md:text-lg">Buscá complejos deportivos por deporte, zona, día y horario aproximado. Después contactá al complejo para confirmar el turno.</p></div><div className="absolute left-4 right-4 top-[290px] md:top-[278px]"><SearchIntentBar criteria={criteria} onChange={updateCriteria} onSearch={() => document.getElementById("results")?.scrollIntoView({ behavior: "smooth" })} /></div></div></section>
    <section className="container mx-auto px-4 pt-28 md:pt-24"><SportRail selected={criteria.sport} onSelect={(sport) => updateCriteria({ sport })} /></section>
    <section id="results" className="container mx-auto scroll-mt-20 px-4 pb-12 pt-6"><div className="mb-3"><h2 className="text-2xl font-bold tracking-tight">Complejos para jugar</h2><p className="mt-1 text-sm text-muted-foreground">Encontrá opciones según el deporte y los filtros seleccionados.</p></div><ResultsToolbar count={filtered.length} criteria={criteria} onChange={updateCriteria} />
      {loading ? <div className="flex min-h-64 items-center justify-center gap-2 text-muted-foreground"><Loader2 className="h-5 w-5 animate-spin" />Cargando complejos…</div> : error ? <Card className="mt-6"><CardContent className="p-8 text-center"><p className="font-medium">No pudimos cargar los complejos.</p><p className="mt-2 text-sm text-muted-foreground">Probá de nuevo en unos minutos.</p></CardContent></Card> : filtered.length === 0 ? <Card className="mt-6 border-dashed"><CardContent className="p-10 text-center"><Search className="mx-auto h-7 w-7 text-emerald-700" /><h3 className="mt-3 text-lg font-semibold">Todavía no encontramos complejos así</h3><p className="mx-auto mt-2 max-w-md text-sm text-muted-foreground">Estamos sumando nuevos espacios. Probá ampliar la zona o quitar características.</p><Button className="mt-5" variant="outline" onClick={() => setParams({}, { replace: true })}><RotateCcw className="mr-2 h-4 w-4" />Limpiar búsqueda</Button></CardContent></Card> : <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,.98fr)_minmax(390px,.9fr)]"><div className="space-y-2">{filtered.map((complex) => <SportComplexCard key={complex.id} complex={complex} onViewDetails={(item) => navigate(`/complex/${item.id}`)} />)}<Button variant="outline" className="w-full bg-card">Ver más complejos <ArrowRight className="ml-2 h-4 w-4" /></Button></div><div className="lg:sticky lg:top-20 lg:h-[590px]"><MapSection complexes={filtered} onSelectComplex={(complex) => navigate(`/complex/${complex.id}`)} /></div></div>}
    </section>
    <section className="container mx-auto grid gap-4 px-4 pb-10 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-2xl border bg-card p-6 text-center"><h2 className="text-xl font-bold">Encontrá una cancha en pocos pasos</h2><div className="mt-6 grid gap-5 sm:grid-cols-3"><div><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><Search className="h-5 w-5" /></span><h3 className="mt-3 text-sm font-bold">1. Elegí tus preferencias</h3><p className="mt-1 text-xs text-muted-foreground">Seleccioná deporte, zona, fecha y horario aproximado.</p></div><div><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><Building2 className="h-5 w-5" /></span><h3 className="mt-3 text-sm font-bold">2. Compará complejos</h3><p className="mt-1 text-xs text-muted-foreground">Revisá ubicación y características publicadas.</p></div><div><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><MessageCircle className="h-5 w-5" /></span><h3 className="mt-3 text-sm font-bold">3. Contactá al complejo</h3><p className="mt-1 text-xs text-muted-foreground">Consultá disponibilidad y confirmá el turno.</p></div></div></div><div className="rounded-2xl bg-emerald-50 p-6 dark:bg-emerald-950/40"><h2 className="text-xl font-bold">¿Tenés un complejo deportivo?</h2><p className="mt-2 max-w-sm text-sm text-foreground/80">Publicá tus canchas, horarios, ubicación y medios de contacto para que más jugadores puedan encontrarte.</p><Button asChild className="mt-5 bg-emerald-700 text-white hover:bg-emerald-800"><a href="/owners/auth">Publicá tu complejo <ArrowRight className="ml-2 h-4 w-4" /></a></Button></div></section>
  </main><footer className="bg-emerald-950 text-white"><div className="container mx-auto grid gap-7 px-4 py-9 text-sm md:grid-cols-4"><div><p className="font-bold">Cancha Libre</p><p className="text-xs text-emerald-100">San Salvador de Jujuy</p><p className="mt-4 text-xs text-white/75">Una plataforma para conectar jugadores con complejos deportivos de la ciudad.</p></div><div><p className="font-semibold">Explorar</p><a className="mt-3 block text-xs text-white/75 hover:text-white" href="#results">Encontrar complejos</a><a className="mt-2 block text-xs text-white/75 hover:text-white" href="/owners/auth">Publicá tu complejo</a></div><div><p className="font-semibold">Información</p><a className="mt-3 block text-xs text-white/75 hover:text-white" href="/terms-of-service">Términos y condiciones</a><a className="mt-2 block text-xs text-white/75 hover:text-white" href="/privacy-policy">Política de privacidad</a></div><div><p className="font-semibold">Contacto</p><a className="mt-3 block text-xs text-white/75 hover:text-white" href="mailto:hola@canchalibre.com.ar">hola@canchalibre.com.ar</a></div></div></footer></div></>;
};
export default Index;
