// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myqjmfficlxrefjhlewo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15cWptZmZpY2x4cmVmamhsZXdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDQ4NDgsImV4cCI6MjA3MzI4MDg0OH0.v8Qo3ooLWtViWRg665oEVgv74bFpXz4WCBtavWCgllA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});