import { Check, RotateCcw, SlidersHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DiscoveryCriteria } from "./discovery-types";

interface Props { count: number; criteria: DiscoveryCriteria; nearbyActive: boolean; onChange: (patch: Partial<DiscoveryCriteria>) => void; }

export function ResultsToolbar({ count, criteria, nearbyActive, onChange }: Props) {
  const hasActiveFilters = criteria.sport !== "todos" || Boolean(criteria.query || criteria.time || criteria.roofOnly || criteria.lightingOnly || criteria.sort !== "relevance");
  const clearFilters = () => onChange({ sport: "todos", query: "", time: "", roofOnly: false, lightingOnly: false, sort: "relevance" });
  return <div className="flex flex-col gap-3 border-y py-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-muted-foreground" aria-live="polite"><span className="font-medium text-foreground">{count}</span> {count === 1 ? "complejo encontrado" : "complejos encontrados"}{criteria.time && <span> · hora preferida {criteria.time}</span>}</p><div className="flex flex-wrap items-center gap-2"><Button type="button" size="sm" variant={criteria.roofOnly ? "secondary" : "outline"} aria-pressed={criteria.roofOnly} onClick={() => onChange({ roofOnly: !criteria.roofOnly })}>{criteria.roofOnly ? <Check className="mr-1.5 h-4 w-4" /> : <SlidersHorizontal className="mr-1.5 h-4 w-4" />}Techada</Button><Button type="button" size="sm" variant={criteria.lightingOnly ? "secondary" : "outline"} aria-pressed={criteria.lightingOnly} onClick={() => onChange({ lightingOnly: !criteria.lightingOnly })}>{criteria.lightingOnly && <Check className="mr-1.5 h-4 w-4" />}Iluminada</Button>{nearbyActive ? <span className="rounded-md border border-emerald-700 bg-emerald-50 px-3 py-2 text-xs font-medium text-emerald-900 dark:border-emerald-400 dark:bg-emerald-950 dark:text-emerald-100">Orden: cercanía</span> : <Select value={criteria.sort} onValueChange={(sort) => onChange({ sort: sort as DiscoveryCriteria["sort"] })}><SelectTrigger className="w-40" aria-label="Ordenar resultados"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="relevance">Más relevantes</SelectItem><SelectItem value="price">Menor precio</SelectItem><SelectItem value="name">Nombre</SelectItem></SelectContent></Select>}{hasActiveFilters && <Button type="button" size="sm" variant="ghost" className="min-h-11" onClick={clearFilters}><RotateCcw className="mr-1.5 h-4 w-4" />Limpiar</Button>}</div></div>;
}
