import { CalendarDays, ChevronDown, Clock3, MapPin, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DISCOVERY_SPORTS, DiscoveryCriteria } from "./discovery-types";

interface Props { criteria: DiscoveryCriteria; onChange: (patch: Partial<DiscoveryCriteria>) => void; onSearch: () => void; }

export function SearchIntentBar({ criteria, onChange, onSearch }: Props) {
  return <form className="rounded-2xl border border-white/30 bg-card p-4 text-card-foreground shadow-2xl backdrop-blur-sm md:p-5" onSubmit={(event) => { event.preventDefault(); onSearch(); }}><div className="flex flex-col gap-4 lg:flex-row lg:items-end"><div className="min-w-0 flex-1"><Label htmlFor="discovery-sport" className="text-xs font-semibold uppercase tracking-[.12em] text-muted-foreground">Deporte</Label><Select value={criteria.sport} onValueChange={(sport) => onChange({ sport })}><SelectTrigger id="discovery-sport" className="mt-1 min-h-11"><SelectValue placeholder="Elegí un deporte" /></SelectTrigger><SelectContent>{DISCOVERY_SPORTS.map((sport) => <SelectItem key={sport.id} value={sport.id}>{sport.label}</SelectItem>)}</SelectContent></Select></div><div className="min-w-0 flex-[1.45]"><Label htmlFor="discovery-location" className="text-xs font-semibold uppercase tracking-[.12em] text-muted-foreground">Zona o barrio</Label><div className="relative mt-1"><MapPin className="pointer-events-none absolute left-3 top-3.5 h-4 w-4 text-muted-foreground" /><Input id="discovery-location" value={criteria.query} onChange={(event) => onChange({ query: event.target.value })} className="min-h-11 pl-9" placeholder="Ej. Centro, Alto Comedero" /></div></div><Button type="submit" className="min-h-11 bg-emerald-800 text-white hover:bg-emerald-900"><Search className="mr-2 h-4 w-4" />Ver en el mapa</Button></div><details className="group mt-4 border-t pt-3"><summary className="flex min-h-11 cursor-pointer list-none items-center gap-2 text-sm font-medium text-foreground"><ChevronDown className="h-4 w-4 transition-transform group-open:rotate-180" />Preferencias de turno <span className="font-normal text-muted-foreground">(opcionales)</span></summary><div className="grid gap-3 pt-2 sm:grid-cols-2"><div><Label htmlFor="discovery-date" className="text-xs font-semibold uppercase tracking-[.12em] text-muted-foreground">Día</Label><div className="relative mt-1"><CalendarDays className="pointer-events-none absolute left-3 top-3.5 h-4 w-4 text-muted-foreground" /><Input id="discovery-date" className="min-h-11 pl-9" type="date" value={criteria.date} onChange={(event) => onChange({ date: event.target.value })} /></div></div><div><Label htmlFor="discovery-time" className="text-xs font-semibold uppercase tracking-[.12em] text-muted-foreground">Hora aproximada</Label><div className="relative mt-1"><Clock3 className="pointer-events-none absolute left-3 top-3.5 h-4 w-4 text-muted-foreground" /><Input id="discovery-time" className="min-h-11 pl-9" type="time" value={criteria.time} onChange={(event) => onChange({ time: event.target.value })} /></div></div></div></details></form>;
}
